name: okrutnik
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'
      - name: Download Okrutnik
        run: |
          wget https://raw.githubusercontent.com/c0m4r/okrutnik/main/okrutnik.sh
          chmod +x okrutnik.sh
      - name: Download Target
        run: |
          wget https://files.pythonhosted.org/packages/b7/06/6b1ad0ae8f97d7a0d6f6ad640db10780578999e647a9593512ceb6f06469/pip-23.3.2.tar.gz
          tar -xvf pip-23.3.2.tar.gz
      - name: Print help
        run: ./okrutnik.sh --help
      - name: Deploy
        run: ./okrutnik.sh --install
      - name: Test correct code
        run: |
          wget https://pastebin.com/raw/pRkMguPA -O test.py
          ./okrutnik.sh --stop test.py
      - name: Test code which sucks
        run: ./okrutnik.sh pip-23.3.2/setup.py || true
      - name: Test code which sucks and exit on first error
        run: ./okrutnik.sh --stop pip-23.3.2/setup.py || true
      - name: Uninstall
        run: ./okrutnik.sh --uninstall <<< "y"
